import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), 'data');
const DATA_FILE = path.join(DATA_DIR, 'store.json');
fs.mkdirSync(DATA_DIR,{recursive:true});
const initial={objects:{},graphs:{},events:[],invites:{},receipts:{},deliveries:{},outbox:{},peers:{}};
const state=fs.existsSync(DATA_FILE)?JSON.parse(fs.readFileSync(DATA_FILE,'utf8')):initial;
for(const k of Object.keys(initial)) if(state[k]===undefined) state[k]=structuredClone(initial[k]);
const RATE_WINDOW=Number(process.env.RATE_WINDOW_MS||60000);
const RATE_LIMIT=Number(process.env.RATE_LIMIT||120);
const VERSION='0.10';
const DATABASE_URL=process.env.DATABASE_URL||'';
let db=null;
if(DATABASE_URL){ try { const { neon } = await import('@neondatabase/serverless'); db=neon(DATABASE_URL); } catch(e){ console.error('Postgres adapter unavailable:',e.message); } }
const INVITE_TTL_MS=Number(process.env.INVITE_TTL_MS||86400000);
const INVITE_MAX_USES=Number(process.env.INVITE_MAX_USES||3);
const CAPABILITY_SECRET=process.env.CAPABILITY_SECRET||process.env.WEBHOOK_SECRET||'development-capability-secret';
const rateBuckets=new Map();
function clientKey(req){return req.headers['x-forwarded-for']?.split(',')[0]?.trim()||req.socket.remoteAddress||'unknown';}
function rateOk(req){const k=clientKey(req),now=Date.now();let b=rateBuckets.get(k);if(!b||now-b.start>RATE_WINDOW)b={start:now,count:0};b.count++;rateBuckets.set(k,b);return b.count<=RATE_LIMIT;}
function discovery(){return Object.values(state.objects).filter(o=>o.state==='pending'&&o.inviteToken&&o.discoverable!==false).slice(-100).map(o=>({id:o.id,graphId:o.graphId,actorId:o.actorId,title:o.title,description:o.description,createdAt:o.createdAt,protocol:`${baseUrl()}/protocol`,entry:`${baseUrl()}${inviteUrl(o.inviteToken)}`}));}
function protocolManifest(){return {protocol:'internet-objects',version:VERSION,capabilities:['state','actor','lineage','invite','capability','events','webhooks','receipts','discovery','federation','outbox'],security:{inviteTtlMs:INVITE_TTL_MS,maxInviteUses:INVITE_MAX_USES},endpoints:{discovery:'/api/discover',events:'/api/events',receipts:'/api/receipts',health:'/api/health',protocol:'/api/protocol',federation:'/api/federation/ingest'},semantics:{pending:'awaiting actor action',resolved:'actor action recorded',propagated:'next actor state created',completed:'graph terminal state reached'},federation:{manifest:'/.well-known/internet-objects',ingest:'/api/federation/ingest',events:'/api/federation/events'}};}
function save(){fs.writeFileSync(DATA_FILE,JSON.stringify(state,null,2));}
async function dbInit(){if(!db)return;const sqls=[`create table if not exists io_objects(id text primary key, graph_id text, actor_id text, state text not null, payload jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`,`create table if not exists io_graphs(id text primary key, status text not null, payload jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`,`create table if not exists io_events(id text primary key, type text not null, payload jsonb not null, created_at timestamptz not null default now())`,`create table if not exists io_invites(token text primary key, object_id text not null, actor_id text, signature text not null, expires_at timestamptz, uses integer not null default 0, max_uses integer not null default 3, created_at timestamptz not null default now())`,`create table if not exists io_outbox(id text primary key, kind text not null, graph_id text, event_type text, payload jsonb not null, status text not null default 'pending', attempts integer not null default 0, next_attempt_at timestamptz not null default now(), completed_at timestamptz, error text)`,`create index if not exists io_outbox_pending_idx on io_outbox(status,next_attempt_at)`,`create table if not exists io_peers(id text primary key, url text unique not null, payload jsonb not null, created_at timestamptz not null default now(), last_seen_at timestamptz)`];for(const q of sqls)await db(q);}
async function dbSync(){if(!db)return;for(const o of Object.values(state.objects))await db`insert into io_objects(id,graph_id,actor_id,state,payload,created_at,updated_at) values(${o.id},${o.graphId||null},${o.actorId||null},${o.state},${JSON.stringify(o)},to_timestamp(${o.createdAt/1000}),now()) on conflict(id) do update set state=excluded.state,payload=excluded.payload,updated_at=now()`;for(const g of Object.values(state.graphs))await db`insert into io_graphs(id,status,payload,created_at,updated_at) values(${g.id},${g.status},${JSON.stringify(g)},to_timestamp(${g.createdAt/1000}),now()) on conflict(id) do update set status=excluded.status,payload=excluded.payload,updated_at=now()`;}
async function persist(){save();if(db)await dbSync();}
function id(){return crypto.randomBytes(7).toString('base64url');}
function inviteToken(){return crypto.randomBytes(18).toString('base64url');}
function capabilitySignature(token){return crypto.createHmac('sha256',CAPABILITY_SECRET).update(token).digest('base64url');}
function inviteFor(objectId, actorId){const token=inviteToken();state.invites[token]={token,objectId,actorId,createdAt:Date.now(),expiresAt:Date.now()+INVITE_TTL_MS,usedAt:null,uses:0,signature:capabilitySignature(token)};save();event('invite_created',{token,objectId,actorId});return token;}
function inviteUrl(token){const inv=state.invites[token];const sig=inv?.signature||capabilitySignature(token);return `/r/${token}.${sig}`;}
function parseCapability(raw){const [token,sig]=String(raw||'').split('.');const inv=state.invites[token];if(!inv||!sig||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(inv.signature||'')))return null;if(inv.expiresAt&&Date.now()>inv.expiresAt)return null;if(inv.uses>=INVITE_MAX_USES)return null;return inv;}
function baseUrl(){return process.env.PUBLIC_BASE_URL||`http://localhost:${process.env.PORT||3000}`;}
function signPayload(secret, body){return crypto.createHmac('sha256',secret).update(body).digest('hex');}
async function deliverWebhook(graph,eventType,payload){const url=graph.webhookUrl;if(!url)return null;const secret=graph.webhookSecret||process.env.WEBHOOK_SECRET||'';const body=JSON.stringify({id:id(),type:eventType,createdAt:Date.now(),data:payload});const headers={'content-type':'application/json','x-internet-object-event':eventType};if(secret)headers['x-internet-object-signature']=signPayload(secret,body);const did=id();state.deliveries[did]={id:did,graphId:payload.graphId||null,type:eventType,url,status:'pending',attempts:0,createdAt:Date.now()};save();try{const r=await fetch(url,{method:'POST',headers,body});state.deliveries[did].attempts=1;state.deliveries[did].status=r.ok?'delivered':'failed';state.deliveries[did].statusCode=r.status;state.deliveries[did].completedAt=Date.now();save();event('webhook_delivery',{deliveryId:did,graphId:payload.graphId||null,type:eventType,status:state.deliveries[did].status});return state.deliveries[did];}catch(e){state.deliveries[did].attempts=1;state.deliveries[did].status='failed';state.deliveries[did].error=e.message;save();event('webhook_delivery',{deliveryId:did,graphId:payload.graphId||null,type:eventType,status:'failed'});return state.deliveries[did];}}
function receiptFor(graph){const rid=id();const r={id:rid,graphId:graph.id||null,status:'completed',issuedAt:Date.now(),objects:Object.values(state.objects).filter(o=>o.graphId===graph.id).map(o=>({id:o.id,actorId:o.actorId,answer:o.answer,state:o.state}))};state.receipts[rid]=r;save();return r;}
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(data));}
async function body(req){let s='';for await(const c of req)s+=c;return JSON.parse(s||'{}')}
function event(type,payload={}){state.events.push({id:id(),type,at:Date.now(),...payload});if(state.events.length>10000)state.events=state.events.slice(-10000);save()}
function compileDeterministic(prompt){
 const lower=prompt.toLowerCase();
 const n=Number((prompt.match(/\b(\d+)\s*(people|persons|users|participants|humans|reviewers|approvers)\b/i)||[])[1])||2;
 const count=Math.max(2,Math.min(20,n));
 const kind=/review|approve|approval|verify|verification/.test(lower)?'review':/vote|choose|pick|select|decision|decide/.test(lower)?'decision':'task';
 const sequential=/then|after|next|in order|sequential|one by one|each/.test(lower);
 const action=kind==='review'?'review':kind==='decision'?'decide':'complete';
 const actors=Array.from({length:count},(_,i)=>({id:`actor_${i+1}`,role:i===0?'creator':`participant_${i}`,action,required:true}));
 return {version:VERSION,intent:prompt,kind,actors,transitions:actors.slice(0,-1).map((a,i)=>({from:a.id,to:actors[i+1].id,when:'resolved'})),resolution:{mode:sequential?'sequential':'all_required'}};
}
async function compileWithAI(prompt){
 const key=process.env.AI_API_KEY||process.env.OPENAI_API_KEY;if(!key)return null;
 const base=process.env.AI_BASE_URL||'https://api.openai.com/v1',model=process.env.AI_MODEL;if(!model) return null;
 const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:'Compile the process into JSON: {kind,actors:[{id,role,action,required}],transitions:[{from,to,when}],resolution:{mode}}. Max 20 actors. First actor creator. mode sequential or all_required. No prose.'},{role:'user',content:prompt}]})});
 if(!r.ok)throw Error(`AI ${r.status}`);const d=await r.json();return {version:VERSION+'-ai',intent:prompt,...JSON.parse(d.choices?.[0]?.message?.content||'{}')};
}
function graphObject(gid,g,actorIndex,parent=null){const actor=g.actors[actorIndex];const oid=id();const o={id:oid,graphId:gid,actorId:actor.id,actorIndex,discoverable:g.discoverable!==false,title:g.intent.slice(0,100),description:`${actor.role}: ${actor.action}. Resolve this state to activate the next actor.`,choices:g.kind==='decision'?['Approve','Reject']:['Complete','Needs changes'],state:'pending',createdAt:Date.now(),visited:0,resolvedAt:null,resolvedBy:null,answer:null,parentObjectId:parent,childObjectId:null};state.objects[oid]=o;return o;}
function publicObject(o){return {...o,url:`/o/${o.id}?actor=${encodeURIComponent(o.actorId)}` ,inviteUrl:o.inviteToken?inviteUrl(o.inviteToken):null}}
function activate(gid){const g=state.graphs[gid];if(!g)return null;if(g.rootObjectId&&state.objects[g.rootObjectId])return state.objects[g.rootObjectId];const o=graphObject(gid,g,0);o.inviteToken=inviteFor(o.id,o.actorId);g.rootObjectId=o.id;g.status='active';g.startedAt=Date.now();event('activate',{graphId:gid,objectId:o.id,actorId:o.actorId});deliverWebhook(g,'object.activated',{graphId:gid,objectId:o.id,actorId:o.actorId,publicUrl:`${baseUrl()}${inviteUrl(o.inviteToken)}`});return o;}
function advance(o){const g=state.graphs[o.graphId];const nextIndex=o.actorIndex+1;if(!g||nextIndex>=g.actors.length)return null;const next=graphObject(o.graphId,g,nextIndex,o.id);next.inviteToken=inviteFor(next.id,next.actorId);o.childObjectId=next.id;event('propagate',{graphId:o.graphId,parentObjectId:o.id,objectId:next.id,actorId:next.actorId,chainIndex:next.actorIndex});deliverWebhook(g,'object.propagated',{graphId:o.graphId,parentObjectId:o.id,objectId:next.id,actorId:next.actorId,publicUrl:`${baseUrl()}${inviteUrl(next.inviteToken)}`});return next;}
function stats(){const ev=state.events;const visits=ev.filter(e=>e.type==='visit');const resolves=ev.filter(e=>e.type==='resolve');const propagated=ev.filter(e=>e.type==='propagate');const uniqueActors=new Set(visits.map(e=>e.actorId).filter(Boolean));const completedGraphs=Object.values(state.graphs).filter(g=>g.status==='completed').length;return {version:VERSION,objects:Object.keys(state.objects).length,graphs:Object.keys(state.graphs).length,activeGraphs:Object.values(state.graphs).filter(g=>g.status==='active').length,completedGraphs,visits:visits.length,uniqueActors:uniqueActors.size,resolutions:resolves.length,propagations:propagated.length,conversion:visits.length?Number((resolves.length/visits.length).toFixed(3)):0};}
const pages={index:fs.readFileSync(path.join(process.cwd(),'public/index.html'),'utf8'),object:fs.readFileSync(path.join(process.cwd(),'public/object.html'),'utf8'),graph:fs.readFileSync(path.join(process.cwd(),'public/graph.html'),'utf8'),dashboard:fs.readFileSync(path.join(process.cwd(),'public/dashboard.html'),'utf8'),protocol:fs.readFileSync(path.join(process.cwd(),'public/protocol.html'),'utf8')};
function queueDelivery(graph,eventType,payload){if(!graph?.webhookUrl)return null;const qid=id();state.outbox[qid]={id:qid,kind:'webhook',graphId:graph.id||payload.graphId||null,eventType,payload,attempts:0,status:'pending',nextAttemptAt:Date.now()};save();return qid;}
async function processOutbox(){for(const q of Object.values(state.outbox)){if(q.status!=='pending'||q.nextAttemptAt>Date.now())continue;const g=q.graphId?state.graphs[q.graphId]:null;if(q.kind!=='webhook'||!g?.webhookUrl){q.status='discarded';continue}q.attempts++;try{const bodyText=JSON.stringify({id:q.id,type:q.eventType,createdAt:Date.now(),data:q.payload});const headers={'content-type':'application/json','x-internet-object-event':q.eventType,'x-internet-object-delivery':q.id};if(g.webhookSecret)headers['x-internet-object-signature']=signPayload(g.webhookSecret,bodyText);const r=await fetch(g.webhookUrl,{method:'POST',headers,body:bodyText});if(r.ok){q.status='delivered';q.completedAt=Date.now();}else throw new Error(`HTTP ${r.status}`)}catch(e){q.error=e.message;if(q.attempts>=5){q.status='failed';q.completedAt=Date.now()}else q.nextAttemptAt=Date.now()+Math.min(300000,1000*2**(q.attempts-1))}save()}}
setInterval(()=>processOutbox().catch(()=>{}),1000).unref();
setInterval(()=>dbSync().catch(e=>console.error('db sync:',e.message)),5000).unref();
dbInit().then(()=>dbSync()).catch(e=>console.error('db init:',e.message));
function federationManifest(){return {...protocolManifest(),issuer:baseUrl(),publishedAt:Date.now()};}
function federationEvent(event){const payload={protocol:'internet-objects',version:VERSION,issuer:baseUrl(),event};const body=JSON.stringify(payload);return {...payload,signature:signPayload(process.env.FEDERATION_SECRET||CAPABILITY_SECRET,body)};}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');
 if(!rateOk(req))return json(res,429,{error:'rate_limited',retryAfterMs:RATE_WINDOW});
 if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}
 if(req.method==='GET'&&u.pathname==='/')return res.writeHead(200,{'content-type':'text/html'}),res.end(pages.index);
 if(req.method==='GET'&&u.pathname==='/protocol')return res.writeHead(200,{'content-type':'text/html'}),res.end(pages.protocol);
 if(req.method==='GET'&&u.pathname==='/dashboard')return res.writeHead(200,{'content-type':'text/html'}),res.end(pages.dashboard);
 if(req.method==='GET'&&u.pathname.startsWith('/r/')){const raw=u.pathname.split('/')[2],inv=parseCapability(raw);if(!inv)return res.writeHead(404),res.end('Invite not found');const o=state.objects[inv.objectId];if(!o)return res.writeHead(410),res.end('State no longer exists');inv.uses++;inv.usedAt=Date.now();save();event('invite_open',{token:inv.token,objectId:o.id,actorId:inv.actorId,uses:inv.uses});return res.writeHead(302,{location:`/o/${o.id}?actor=${encodeURIComponent(inv.actorId)}&invite=${encodeURIComponent(inv.token)}`}),res.end()}
 if(req.method==='GET'&&u.pathname.startsWith('/o/')){const oid=u.pathname.split('/')[2],o=state.objects[oid];if(!o)return res.writeHead(404),res.end('Object not found');o.visited++;event('visit',{objectId:oid,graphId:o.graphId,actorId:u.searchParams.get('actor')||o.actorId,ref:req.headers.referer||null});return res.writeHead(200,{'content-type':'text/html'}),res.end(pages.object)}
 if(req.method==='GET'&&u.pathname.startsWith('/g/'))return res.writeHead(200,{'content-type':'text/html'}),res.end(pages.graph);
 if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,...stats(),ai:!!(process.env.AI_API_KEY||process.env.OPENAI_API_KEY)});
 if(req.method==='GET'&&u.pathname==='/api/stats')return json(res,200,{...stats(),pendingObjects:Object.values(state.objects).filter(o=>o.state==='pending').length,inviteConversion:(Object.keys(state.invites).length?Number((state.events.filter(e=>e.type==='resolve').length/Math.max(1,state.events.filter(e=>e.type==='invite_open').length)).toFixed(3)):0),invites:Object.keys(state.invites).length,inviteOpens:state.events.filter(e=>e.type==='invite_open').length,webhookDeliveries:Object.keys(state.deliveries).length,outbox:Object.values(state.outbox).filter(x=>x.status==='pending').length,receipts:Object.keys(state.receipts).length});
 if(req.method==='GET'&&u.pathname==='/api/events')return json(res,200,{events:state.events.slice(-200)});
 if(req.method==='GET'&&u.pathname==='/api/discover')return json(res,200,{protocol:protocolManifest(),objects:discovery()});
 if(req.method==='GET'&&u.pathname==='/api/protocol')return json(res,200,protocolManifest());
 if(req.method==='GET'&&u.pathname==='/.well-known/internet-objects')return json(res,200,federationManifest());
 if(req.method==='GET'&&u.pathname==='/api/outbox')return json(res,200,{items:Object.values(state.outbox).slice(-100).reverse()});
 if(req.method==='GET'&&u.pathname==='/api/peers')return json(res,200,{peers:Object.values(state.peers)});
 if(req.method==='POST'&&u.pathname==='/api/federation/register'){const b=await body(req);if(!b.url||!String(b.url).startsWith('http'))return json(res,400,{error:'url is required'});const pid=id();state.peers[pid]={id:pid,url:String(b.url).replace(/\/$/,''),name:b.name||null,createdAt:Date.now(),lastSeenAt:null};save();return json(res,201,{peer:state.peers[pid]});}
 if(req.method==='POST'&&u.pathname==='/api/federation/ingest'){const b=await body(req);if(!b.event||b.protocol!=='internet-objects')return json(res,400,{error:'invalid federation event'});const secret=process.env.FEDERATION_SECRET||CAPABILITY_SECRET;const unsigned={protocol:b.protocol,version:b.version,issuer:b.issuer,event:b.event};const expected=signPayload(secret,JSON.stringify(unsigned));if(b.signature&&b.signature!==expected)return json(res,401,{error:'invalid federation signature'});const eid=id();state.events.push({id:eid,type:'federated_event',at:Date.now(),issuer:b.issuer||null,remoteEvent:b.event,verified:!!b.signature});save();return json(res,202,{accepted:true,verified:!!b.signature,eventId:eid});}
 if(req.method==='GET'&&u.pathname==='/api/receipts'){return json(res,200,{receipts:Object.values(state.receipts).slice(-100).reverse()})}
 if(req.method==='GET'&&u.pathname.startsWith('/api/receipts/')){const rid=u.pathname.split('/')[3],r=state.receipts[rid];return r?json(res,200,{receipt:r}):json(res,404,{error:'receipt not found'})}
 if(req.method==='GET'&&u.pathname==='/api/objects'){return json(res,200,{objects:Object.values(state.objects).sort((a,b)=>b.createdAt-a.createdAt).slice(0,100).map(publicObject)})}
 let m=u.pathname.match(/^\/api\/objects\/([^/]+)$/);if(req.method==='GET'&&m){const o=state.objects[m[1]];return o?json(res,200,{object:publicObject(o)}):json(res,404,{error:'object not found'})}
 if(req.method==='POST'&&u.pathname==='/api/compile'){const b=await body(req),prompt=String(b.prompt||'').trim();if(!prompt)return json(res,400,{error:'prompt is required'});let g=null;try{g=await compileWithAI(prompt)}catch{}if(!g)g=compileDeterministic(prompt);g.discoverable=b.discoverable!==false;g.webhookUrl=typeof b.webhookUrl==='string'&&b.webhookUrl.startsWith('http')?b.webhookUrl:null;g.webhookSecret=typeof b.webhookSecret==='string'?b.webhookSecret:null;const gid=id();g.id=gid;g.status='draft';g.createdAt=Date.now();state.graphs[gid]=g;save();event('compile',{graphId:gid,ai:g.version.endsWith('-ai')});return json(res,201,{graph:g,graphId:gid,url:`/g/${gid}`,compiler:g.version.endsWith('-ai')?'ai':'deterministic'});}
 m=u.pathname.match(/^\/api\/graphs\/([^/]+)$/);if(req.method==='GET'&&m){const g=state.graphs[m[1]];return g?json(res,200,{graph:g,rootObject:g.rootObjectId?publicObject(state.objects[g.rootObjectId]):null}):json(res,404,{error:'graph not found'})}
 m=u.pathname.match(/^\/api\/graphs\/([^/]+)\/activate$/);if(req.method==='POST'&&m){const o=activate(m[1]);return o?json(res,201,{object:publicObject(o),publicUrl:`${baseUrl()}${o.inviteToken?inviteUrl(o.inviteToken):`/o/${o.id}`}`}):json(res,404,{error:'graph not found'})}
 if(req.method==='POST'&&u.pathname==='/api/objects'){const b=await body(req),choices=Array.isArray(b.choices)?b.choices.filter(x=>typeof x==='string'&&x.trim()).slice(0,8):[];if(!b.title||!b.description||choices.length<2)return json(res,400,{error:'title, description and at least 2 choices are required'});const oid=id();const o={id:oid,title:String(b.title).trim(),description:String(b.description).trim(),choices,state:'pending',createdAt:Date.now(),visited:0,resolvedAt:null,resolvedBy:null,answer:null,parentObjectId:b.parentObjectId||null,childObjectId:null};state.objects[oid]=o;event('create',{objectId:oid});return json(res,201,{object:publicObject(o)});}
 m=u.pathname.match(/^\/api\/objects\/([^/]+)$/);if(req.method==='POST'&&m){const o=state.objects[m[1]];if(!o)return json(res,404,{error:'object not found'});if(o.state==='resolved')return json(res,200,{object:publicObject(o),nextObject:o.childObjectId?publicObject(state.objects[o.childObjectId]):null});const b=await body(req);if(!o.choices.includes(b.answer))return json(res,400,{error:'invalid choice'});o.state='resolved';o.answer=b.answer;o.resolvedAt=Date.now();o.resolvedBy=b.actorId||o.actorId;event('resolve',{objectId:o.id,graphId:o.graphId||null,actorId:o.resolvedBy});if(o.graphId)queueDelivery(state.graphs[o.graphId],'object.resolved',{graphId:o.graphId,objectId:o.id,actorId:o.resolvedBy,answer:o.answer});let next=null;if(o.graphId)next=advance(o);if(o.graphId&&next===null){state.graphs[o.graphId].status='completed';state.graphs[o.graphId].completedAt=Date.now();event('complete',{graphId:o.graphId});const receipt=receiptFor(state.graphs[o.graphId]);queueDelivery(state.graphs[o.graphId],'graph.completed',{graphId:o.graphId,receiptId:receipt.id,receiptUrl:`${baseUrl()}/api/receipts/${receipt.id}`});return json(res,200,{object:publicObject(o),nextObject:next?publicObject(next):null,completed:!next&&!!o.graphId,receipt:receipt});}}
 res.writeHead(404);res.end('Not found');}catch(e){json(res,500,{error:e.message||'internal error'})}});
server.listen(process.env.PORT||3000,()=>console.log(`Internet Objects ${VERSION} listening on http://localhost:${process.env.PORT||3000}`));
